spring:
  application:
    name: findex

  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: BDOsTvqCuwEAPtZLMeYvqfkkXfWadZon
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        jdbc.time_zone: UTC
        default_batch_fetch_size: 1000
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        format_sql: false
        highlight_sql: false
        use_sql_comments: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

auto-sync:
  scheduler:
    enabled: true
    cron: "0 5 6 * * *"
    zone: "Asia/Seoul"

api:
  service-key: "4e45f20039574765ef0b52364e6ba488dde012627aef89847dccacb39fb77f0d"
  stock-url: "https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService/getStockMarketIndex"
