spring:
  application:
    name: findex
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: BDOsTvqCuwEAPtZLMeYvqfkkXfWadZon
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        jdbc.time_zone: UTC

# log
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info

auto-sync:
  scheduler:
    enabled: true
    cron: "0 5 6 * * *"
    zone: "Asia/Seoul"

# API
api:
  service-key: '4e45f20039574765ef0b52364e6ba488dde012627aef89847dccacb39fb77f0d'
  stock-url: 'https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService/getStockMarketIndex'
